name: Automated E2E test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Start frontend for E2E testing
      run: |
        cd src/frontend
        npm install
        npm start
    - name: Cypress run
      uses: cypress-io/github-action@v1
