name: Automated E2E test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        working-directory: src/frontend 
        start: yarn start
        wait-on: 'http://localhost:3000'
