name: Automated E2E test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start Web App locally
      run: |
        cd src/frontend
        yarn install
        yarn start &
    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        working-directory: src/frontend 
        wait-on: 'http://localhost:3000'
